//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.gpfcomics.LinodeDynamicDNS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.gpfcomics.LinodeDynamicDNS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.linode.com/?api_key=.
        /// </summary>
        internal static string APICallHeader {
            get {
                return ResourceManager.GetString("APICallHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIKey.
        /// </summary>
        internal static string APIKeyRegKeyName {
            get {
                return ResourceManager.GetString("APIKeyRegKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string DomainSubKeyName {
            get {
                return ResourceManager.GetString("DomainSubKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPF Comics.
        /// </summary>
        internal static string GPFRegKeyName {
            get {
                return ResourceManager.GetString("GPFRegKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastRan.
        /// </summary>
        internal static string LastRanRegKeyName {
            get {
                return ResourceManager.GetString("LastRanRegKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        internal static string SuccessRegKeyName {
            get {
                return ResourceManager.GetString("SuccessRegKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinodeDynamicDNS.
        /// </summary>
        internal static string UpdaterRegKeyName {
            get {
                return ResourceManager.GetString("UpdaterRegKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/gpfjeff/linode-dynamic-dns.
        /// </summary>
        internal static string WebsiteURL {
            get {
                return ResourceManager.GetString("WebsiteURL", resourceCulture);
            }
        }
    }
}
